language: python

matrix:
    include:
        - python: 2.6
          env: TEST_TYPE=test
        - python: 2.7
          env: TEST_TYPE=test
        - python: 2.7
          env: TEST_TYPE=check
        - python: 3.3
          env: TEST_TYPE=test
        - python: 3.4
          env: TEST_TYPE=test
        - python: 3.5
          env: TEST_TYPE=test
        - python: 3.6
          env: TEST_TYPE=test

sudo: false
install:
  - if [[ $TEST_TYPE == 'check' ]]; then pip install -r requirements-dev.txt; fi
  - python scripts/ci/install
script:
  - make $TEST_TYPE
